# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_DEBUG_URL: ${{ secrets.WEBHOOK_DEBUG_URL }}
        WEBHOOK_ERROR_URL: ${{ secrets.WEBHOOK_ERROR_URL }}

    - name: Make zip file
      run: zip -r ./deploy.zip ./build/libs/fcfs-event-0.0.1.jar ./appspec.yml ./scripts/*
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name code-deploy
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name deploy-group
        --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=deploy.zip
